# this compose file create a wordpress ...

version: "3"

services:
  wordpress:
    image: wordpress
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "coffee"
      WORDPRESS_DB_NAME: wordpress
    networks:
      ohyeah:
        ipv4_address: "128.1.7.21"
  
  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: "coffee"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      ohyeah:
        ipv4_address: "128.1.7.20"

networks:
  ohyeah:
    ipam:
      driver: default
      config:
        - subnet: "128.1.7.0/24"
