# create a ubuntu desktop 

version: '3'
services:
  ubuntu-vnc:
    image: dorowu/ubuntu-desktop-lxde-vnc
    ports:
      - "8080:8080"
    environment:
      - VIRTUAL_PORT=8080
    command: vncserver -geometry 1280x800 -depth 24 && export DISPLAY=:1 && supervisord -n
