---
version: "2.1"
services:
  opera:
    image: lscr.io/linuxserver/opera:latest
    container_name: opera
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
    ports:
      - 3000:3000
    shm_size: "1gb"
    restart: unless-stopped