# Running chromium
version: "2.1"
services:
  chromium:               
    image: lscr.io/linuxserver/chromium:latest
    container_name: chromium
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
    ports:
      - 3000:3000
    shm_size: "2gb"
    restart: unless-stopped