FROM php:7.4-apache

# Sao chép tệp tin website vào trong container
COPY . /var/www/html

# Đảm bảo các phần tử trên tệp tin index.php có quyền thích hợp
RUN chown -R www-data:www-data /var/www/html

# Tiến hành cài đặt các gói mở rộng PHP cần thiết
RUN docker-php-ext-install pdo_mysql

# Expose cổng 80 để truy cập trang web từ môi trường bên ngoài
EXPOSE 80
